apiVersion: v1
data:
  images.json: |-
    [
      "https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcQj03S23J2gCxSsTwyaCeMw3u6-B36vGDZ9voA0v5lsuafmqV2LHkxjhKJsLg_deStIwWl1yloRGTA4VLxtrxQ"
    ]
kind: ConfigMap
metadata:
  name: images-json
  labels:
    app: random-meme
